name: CI (check-all)

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - run: echo 'The triggering workflow failed' && false
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
